kind = "design"
previewPath = "/"
title = "AlmazStat Development Preview"
version = "1.0.0"
id = "XegfDyZt7HqfW2Bb8Ghoy"

[[services]]
localPort = 8081
name = "Component Preview Server"
paths = ["/"]

[services.env]
PORT = "8081"

[services.development]
run = "cd ../.. && pnpm start"
